// Generated by CoffeeScript 2.5.0
(function() {
  module.exports = function(str, split, n) {
    var key, pos, r;
    r = [];
    n = n - 1;
    while (r.length < n) {
      pos = str.indexOf(split);
      if (pos < 0) {
        break;
      }
      key = str.slice(0, pos);
      str = str.slice(pos + 1);
      r.push(key);
    }
    r.push(str);
    return r;
  };

}).call(this);
